### ISSUE TITLE
AdbOptions - property descriptions are switched

### ISSUE THREAD

**Issue by koral--** [google/android-gradle-dsl#1]
http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.AdbOptions.html
```
installOptions	
The time out used for all adb operations.
timeOutInMs	
The list of APK installation options.
```
Description of the `installOptions` is in row of `timeOutInMs` and vice versa.

**Comment by benol** [comment]
Thanks, will be fixed in 2.0 documentation. Keep them coming :)
