### ISSUE TITLE
registerResGeneratingTask() deprecation warning is incorrect.

### ISSUE THREAD

**Issue by ryancerium** [google/android-gradle-dsl#10]
The Gradle deprecation warning for `Variant.registerResGeneratingTask()` gives you incorrect advice.  It says, `registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)`, but the actual function is `registerGeneratedResFolders(FileCollection)`

**Comment by bendowski** [comment]
Please use the main Android issue tracker (https://issuetracker.google.com) for filing bugs that are not about contents of the docs published here.

This has already been fixed in the source code, fix should be visible in the next canary.
