### ISSUE TITLE
how can I support buildtools(19.1.0) in android studio 3.0? 

### ISSUE THREAD

**Issue by gezihua** [google/android-gradle-dsl#12]

**Comment by gezihua** [comment]
I get the message that as 3.0 will not support build tools of 19.1.0, even I get the code that forces check the build tool version。Unfortunately， the project that I support is still use as 3.0.

**Comment by gavra0** [comment]
Please file bugs at https://issuetracker.google.com/issues/new?component=192708&template=840533. There is more information about the process here: https://developer.android.com/studio/report-bugs
