### ISSUE TITLE
moving class to another package lead to duplicate class in apk

### ISSUE THREAD

**Issue by softrice** [google/android-gradle-dsl#15]
1. new project
2. the configure 
`classpath 'com.android.tools.build:gradle:3.1.3'`
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`
3. run ./gradlew assembleDebug
4. moving class to another package
5. run ./gradlew assembleDebug
6. duplicate class in apk
pre
![image](https://user-images.githubusercontent.com/10737613/45859555-88efe500-bd95-11e8-8d3a-f289106021d4.png)
moving Test1 to another package
after
![image](https://user-images.githubusercontent.com/10737613/45859584-a2912c80-bd95-11e8-8179-160b43b6d3e5.png)
two Test1.class in different package

**Comment by gavra0** [comment]
Please file bugs at https://issuetracker.google.com/issues/new?component=192708&template=840533. There is more information about the process here: https://developer.android.com/studio/report-bugs?
