### ISSUE TITLE
aar file is incomplete

### ISSUE THREAD

**Issue by gugocondicho** [google/android-gradle-dsl#2]
Please consider adding some features to aar files:

- Currently an aar file does *not* include dependency information. So if I include an aar file which needs some other dependencies, the project won't compile.

- Please support remote aar files. So I won't need my own maven server to provide a library project. Supporting direct links would be great.

Thanks,

**Comment by benol** [comment]
This repo is only about the DSL documentation, please don't file issues about missing features here. A better place is our bug tracker that we monitor, you can file a feature request here: https://code.google.com/p/android/issues/entry?template=Tools%20feature%20request

But to address your point: we do support remote AAR files, see for example https://github.com/jdeferred/jdeferred - you specify the "@aar" classifier and it should work. The dependency information is not stored in the AAR itself, rather in the standard pom.xml file, just like for jar files.
