### ISSUE TITLE
when change build 1.5.0 to 2.2.0,the strip .so file is reduced

### ISSUE THREAD

**Issue by zhangmingxingAtGit** [google/android-gradle-dsl#6]
this is the so file,file size is 216kb:
![source file](https://cloud.githubusercontent.com/assets/6938111/19211627/a2cbf7b0-8d73-11e6-9e84-2db2c632e9c4.png)
this is after strip task in build tools 2.2.0,the strip file is reduced to 9kb
![after build](https://cloud.githubusercontent.com/assets/6938111/19211628/a726c6b4-8d73-11e6-8c31-1f76b0c7895c.png)

who can tell me why?

**Comment by benol** [comment]
This doesn't seem to be an issue with our DSL documentation. Please file a bug on http://b.android.com about build problems.

**Comment by zhangmingxingAtGit** [comment]
but when it is build tools 1.5.0,no this problem
