### ISSUE TITLE
No information about PackagingOptions.doNotStrip in Android Gradle plugin 2.2

### ISSUE THREAD

**Issue by idyatlov** [google/android-gradle-dsl#7]
In Android Gradle plugin 2.2 implemented new mechanism of stripping debug symbols from native libraries in release builds - it used by default, but there is absolutely no information about it in changelogs or DSL documentation. I had needed to manually look into code of plugin to obtain this information (because after stripping symbols some DRM libraries became unusable), and discover that in PackagingOptions appeared method doNotStrip(String filter), similar to other methods in this class.
I think that this is big miss in documentation, which can silently affect other people's projects as well as my.

**Comment by benol** [comment]
Thanks for catching this, will be added for 2.3 documentation.
