### ISSUE TITLE
Inconsistent pseudoLocalesEnabled documentation

### ISSUE THREAD

**Issue by koral--** [google/android-gradle-dsl#8]
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html#com.android.build.gradle.internal.dsl.BuildType:pseudoLocalesEnabled

Documentation says `generate pseudo locale` and `fake pseudo locales (en-XA and ar-XB) will be added to the APK`. However not locales but resources for that locales are generated. Moreover depending on e.g. `aaptOptions.additionalParameters` they might not be added to APK even if generated.

New proposed text:
```
Whether to generate resources for pseudolocales.

If enabled, string and plural resources for 2 pseudolocales (en-XA and ar-XB) will be generated. They can be added to the APK to help test internationalization support in the app.
```

**Comment by gavra0** [comment]
Please file bugs at https://issuetracker.google.com/issues/new?component=192708&template=840533. There is more information about the process here: https://developer.android.com/studio/report-bugs
