### ISSUE TITLE
Feature request: wildcards in resConfigs

### ISSUE THREAD

**Issue by avakhrushev** [google/android-gradle-dsl#9]
It would be nice if resConfigs could accept filters with wildcards, such as 'en-r??'. Currently there isn't an easy way to whitelist a language with all its regional variations, which makes resConfigs hard to use in all but most trivial cases.

**Comment by bendowski** [comment]
Please use the main Android issue tracker for requests like this. I made a copy under https://issuetracker.google.com/69240488
